name: test action

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    # container: node:17.6.0
    # strategy:
    #   matrix:
    #     node-version: [14.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # - run: node --version > ./diff
      # - run: npm --version >> ./diff
      - name: Git checkout 
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Build and run docker image
        id: dock
        run: |
          docker run --rm -v ./shared:/shared alpine:3.10
          cd shared
          rm file
          echo some_var=some_text > new_file
          cat new_file >> $GITHUB_OUTPUT
        # run: docker run -it $(docker build - < Dockerfile)
      # - name: Build docker images
      #   run: docker build local < Dockerfile
      # - name: Run tests
      #   id: dock
      #   run: docker run -it -v $PWD:/ -w/ local
        # with:
        #   args: The ${{ github.event_name }} event triggered this step.
        # run: docker run -it -v $PWD:/ -w/ local make test
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - name: Output list of files edited today
      #   id: diff
      #   run: |
      #     markup_header="### List of files edited today:"
      #     git config user.name "gh-actions bot"
      #     git config user.email "<>"
      #     git log --pretty="format:" --name-only --since="1 day ago" | sort | uniq | cut -d. -f1 > ./diff
      #     cat ./diff | { echo $markup_header ; cat ; } >> $GITHUB_STEP_SUMMARY
      
      # - name: Run Docker
      #   id: dock
      #   uses: 'docker'
      #   image: 'Dockerfile'
      #   with:
      #     args: The ${{ github.event_name }} event triggered this step.
        
      # - name: Build docker images
      #   run: docker compose build
      # - name: Setup database
      #   run: docker compose run setup
      # - name: Run tests
      #   run: docker compose run test

      - name: Add Docker results to diff
        run: |
          echo ${{ steps.dock.outputs.some_var }}" >> ./diff

      - name: Send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message_file: ./diff