name: ping

on:
    schedule:
        # Every 15 minutes:
        -   cron: "*/15 * * * *"

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ping:
    name: Ping
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Git checkout 
        uses: actions/checkout@master
        with:
          fetch-depth: 0
          
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Perform ping
        id: ping
        run: |
          chmod +x check-sites.py
          python check-sites.py
          echo result=$(cat result | wc -c) >> $GITHUB_OUTPUT
          echo $GITHUB_OUTPUT
        env:
          SITES: ${{ secrets.SITES }}

      - name: Send telegram message if some site is down
        uses: appleboy/telegram-action@master
        if: ${{ steps.ping.outputs.result }} != "0"
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message_file: ./result